import type { Recipe } from "@/types/recipe";

export const pantryRecipes: Recipe[] = [
  {
    id: "pasta-cobb-salad",
    title: "Pasta Cobb Salad",
    image: "",
    cookTime: "15 min",
    difficulty: "Easy",
    ingredients: [
      "1 pouch Barilla Ready Pasta Elbows",
      "2 slices bacon, crispy and cut in strips",
      "1 cup iceberg salad, shredded",
      "1 hard-boiled egg, chopped",
      "4 oz grilled chicken breast, sliced",
      "2 ripe plum tomatoes, diced",
      "½ avocado, diced",
      "3 green onions, chopped",
      "¼ cup blue cheese, crumbled",
      "4 oz ranch dressing",
    ],
    pantryIngredients: [
      "Barilla Ready Pasta Elbows",
      "Iceberg salad",
      "Hard-boiled eggs",
      "Green onions",
    ],
    instructions: [
      "Tear corner of Ready Pasta pouch to vent, heat in microwave for one minute; pour on a plate and let cool down.",
      "Toss pasta with all ingredients together in individual-sized serving bowls.",
    ],
    substitutions: [
      "Swap bacon for canned tuna from the Pantry.",
      "Replace blue cheese with any pantry-available cheese.",
    ],
  },
  {
    id: "pasta-salad-tomato-basil",
    title: "Pasta Salad with Tomato Basil Sauce and Cheese",
    image: "",
    cookTime: "10 min",
    difficulty: "Easy",
    ingredients: [
      "1 pouch Barilla Ready Pasta Elbows",
      "1 cup Barilla Tomato & Basil Sauce",
      "2 leaves of basil, julienned",
      "2 tbsp Parmigiano-Reggiano cheese, grated",
    ],
    pantryIngredients: ["Barilla Ready Pasta Elbows", "Basil leaves"],
    instructions: [
      "Tear corner of Ready Pasta pouch to vent, heat for 60 seconds in the microwave.",
      "Warm sauce and basil in a bowl for 2 minutes in the microwave.",
      "Combine pasta with sauce and top with cheese.",
    ],
    substitutions: [
      "Use any canned tomato sauce from the Pantry.",
      "Sprinkle nutritional yeast instead of cheese.",
    ],
  },
  {
    id: "esquite",
    title: "Esquite",
    image: "",
    cookTime: "15 min",
    difficulty: "Easy",
    ingredients: [
      "1 can of sweet corn",
      "1 tbsp butter",
      "Salt to taste",
      "⅓ cup Parmesan cheese or Cotija",
      "Chile powder or Hot Cheetos powder",
      "2 tbsp mayonnaise",
    ],
    pantryIngredients: ["Sweet corn (canned)"],
    instructions: [
      "Start by adding the butter to a frying pan.",
      "Add the corn kernels and cook for 5 minutes over medium heat.",
      "Serve in cups.",
      "Add cheese, mayonnaise on top, and finish with chili powder or Hot Cheetos powder.",
      "Eat as is, or mix. Enjoy!",
    ],
    substitutions: [
      "Use olive oil instead of butter.",
      "Substitute Cotija with any crumbled cheese.",
    ],
  },
  {
    id: "tuna-salad-sandwich",
    title: "Tuna Salad Sandwich",
    image: "",
    cookTime: "15 min",
    difficulty: "Easy",
    ingredients: [
      "1 can tuna",
      "2 medium tomatoes",
      "¼ cup cilantro",
      "A pinch of sea salt",
      "⅛ cup white or red onion",
      "¼ cup cucumber",
      "1 lemon or lime",
      "2 slices of bread",
      "Optional: ¼ cup mayonnaise",
    ],
    pantryIngredients: [
      "Canned tuna",
      "Tomatoes",
      "Cilantro",
      "White or red onion",
      "Cucumber",
      "Lemon or lime",
      "Bread",
    ],
    instructions: [
      "Open the canned tuna. Drain the liquid from the canned tuna. Add the tuna to the bowl.",
      "Wash your tomatoes, cucumber, and onion. Chop the tomatoes, cucumber, and onion into small cubes.",
      "Wash and drain your cilantro and roughly chop the cilantro.",
      "Add the chopped tomatoes, cucumber, onion, and cilantro into the same bowl as the tuna.",
      "Add lemon or lime juice to the bowl.",
      "You may add mayonnaise if you want, and add the sea salt.",
      "Carefully mix your ingredients together.",
      "Can be eaten right away or stored in an airtight container in the refrigerator.",
    ],
    substitutions: [
      "Use canned salmon instead of tuna.",
      "Swap cucumber for any crunchy vegetable available.",
    ],
  },
  {
    id: "tuna-noodle-casserole",
    title: "Tuna Noodle Casserole",
    image: "",
    cookTime: "35 min",
    difficulty: "Medium",
    ingredients: [
      "1 can tuna",
      "½ cup beans and legumes",
      "Pasta noodles",
      "4 cups spinach",
      "¼ cup Alfredo sauce",
      "Oil",
      "Dash of basil",
      "Dash of oregano",
    ],
    pantryIngredients: [
      "Canned tuna",
      "Beans and legumes",
      "Pasta noodles",
      "Spinach",
      "Basil",
      "Oregano",
    ],
    instructions: [
      "Preheat the oven to 400°F.",
      "Cook pasta according to the packaging instructions on the stovetop.",
      "Coat the casserole dish with oil.",
      "Combine all ingredients in the casserole dish.",
    ],
    substitutions: [
      "Use canned chicken instead of tuna.",
      "Swap spinach for any leafy green from the Pantry.",
    ],
  },
  {
    id: "tuna-melts-on-pepper",
    title: "Tuna Melts on Pepper",
    image: "",
    cookTime: "20 min",
    difficulty: "Easy",
    ingredients: [
      "1 can tuna",
      "1 green bell pepper",
      "1 tbsp mayonnaise",
      "⅓ cup mozzarella cheese, shredded",
      "Dash of everything bagel seasoning",
    ],
    pantryIngredients: ["Canned tuna", "Green bell pepper"],
    instructions: [
      "Preheat the oven to 425°F.",
      "Slice peppers into quarters.",
      "Mix tuna and mayonnaise.",
      "Combine all ingredients into a casserole dish.",
      "Bake for 10 minutes.",
      "Remove from the oven, top with cheese.",
      "Bake for another ~3 minutes.",
      "No cheese? Use dairy-free cheese.",
    ],
    substitutions: [
      "Use any color bell pepper available.",
      "Swap mozzarella for any melting cheese.",
    ],
  },
  {
    id: "arugula-chickpea-tuna-salad",
    title: "Arugula Chickpea Tuna Salad",
    image: "",
    cookTime: "15 min",
    difficulty: "Easy",
    ingredients: [
      "2 tbsp olive oil",
      "Arugula",
      "Canned chickpeas",
      "Lemon juice",
      "Canned tuna",
      "Diced red onion",
      "Sesame salad dressing",
      "Garlic powder",
      "Onion powder",
      "Smoked paprika",
      "Cayenne pepper (optional)",
      "Za'atar",
      "Salt",
      "Pepper",
      "Dill seasoning",
      "Optional: nutritional yeast for Vitamin B12",
    ],
    pantryIngredients: [
      "Arugula",
      "Chickpeas (canned)",
      "Canned tuna",
      "Red onion",
      "Garlic powder",
      "Onion powder",
      "Smoked paprika",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Open and drain cans of tuna and chickpeas. Lightly mash tuna after draining.",
      "Dice red onions.",
      "Drizzle olive oil in a bowl and toss in chickpeas to cover in oil.",
      "Mix in garlic powder, onion powder, smoked paprika, cayenne pepper, za'atar, salt, and pepper.",
      "Add tuna and lightly mix it in the bowl.",
      "Top with arugula.",
      "Squeeze lemon juice and add dill seasoning.",
      "Toss salad and your quick meal is ready!",
    ],
    substitutions: [
      "Use any canned beans instead of chickpeas.",
      "Swap arugula for spinach or mixed greens.",
    ],
  },
  {
    id: "spicy-rice-casserole",
    title: "Spicy Rice Casserole",
    image: "",
    cookTime: "25 min",
    difficulty: "Medium",
    ingredients: [
      "3 tbsp canola oil",
      "4 eggs, lightly beaten",
      "½ tsp sesame oil",
      "1 onion, chopped",
      "1 tsp ginger, finely chopped",
      "1 clove garlic, finely chopped",
      "½ hot pepper, deseeded and finely chopped",
      "2 bell peppers, deseeded and finely chopped",
      "1 lb broccoli, chopped",
      "4 cups cooked rice",
      "4 tbsp soy sauce",
      "¼ cup oyster sauce",
    ],
    pantryIngredients: [
      "Eggs",
      "Onion",
      "Ginger",
      "Garlic",
      "Hot pepper",
      "Bell peppers",
      "Broccoli",
      "Cooked rice",
    ],
    instructions: [
      "In a large skillet, heat 1 tbsp canola oil and sesame oil over medium-high heat. Add eggs and stir until cooked through.",
      "Set aside the eggs, wipe the skillet, and add remaining canola oil. Add onion, ginger, garlic, both hot pepper and bell peppers, broccoli, and cooked rice. Increase heat slightly and cook until rice is crispy (about 5 minutes).",
      "In a small bowl, combine oyster sauce with soy sauce. Pour mixture over rice and continue cooking until the rice has absorbed the liquid.",
      "Add cooked eggs back into the skillet and mix. Serve.",
    ],
    substitutions: [
      "Use any available vegetables instead of broccoli or bell peppers.",
      "Substitute oyster sauce with additional soy sauce.",
    ],
  },
  {
    id: "chicken-panang-curry",
    title: "Chicken Panang Curry",
    image: "",
    cookTime: "30 min",
    difficulty: "Medium",
    ingredients: [
      "2 chicken breasts",
      "Panang curry paste or panang curry sauce",
      "Coconut milk (if not using panang curry sauce)",
      "Salt to taste",
      "Oil",
      "¼ cup shallots",
      "1 tbsp thai chilies",
      "¼ tsp curry powder (optional)",
      "Broccoli",
      "Green beans",
      "Chicken broth (optional: low-sodium)",
      "Bok choy",
    ],
    pantryIngredients: [
      "Salt",
      "Broccoli",
      "Green beans",
      "Chicken broth",
      "Bok choy",
    ],
    instructions: [
      "Thoroughly wash bok choy and separate sprigs.",
      "Rinse broccoli and green beans.",
      "Chop up chicken breast into bite-sized pieces. Chop up shallots.",
      "Heat up oil in a large pot and throw in shallots and thai chilis. Cook for a few minutes until shallots start to brown.",
      "Add panang curry paste if not opting for panang curry sauce.",
      "Pour in coconut milk for the paste (if not using panang curry sauce).",
      "Add chicken breast into pot and pour in a small amount of chicken broth and curry powder.",
      "Cover with lid and simmer for 10–12 minutes.",
      "Uncover and add broccoli, green beans, and bok choy.",
      "Cook for an additional 5 minutes. Serve with rice!",
    ],
    substitutions: [
      "Use canned chickpeas or tofu instead of chicken for a vegetarian version.",
      "Swap bok choy for spinach or any leafy green.",
    ],
  },
  {
    id: "chili-stuffed-poblano-peppers",
    title: "Chili Stuffed Poblano Peppers",
    image: "",
    cookTime: "35 min",
    difficulty: "Medium",
    ingredients: [
      "1 lb ground turkey",
      "1 can of chili",
      "¼ tsp salt",
      "1½ cups shredded Mexican cheese",
      "1 medium tomato",
      "4 green onions",
      "4 poblano peppers",
      "1 tsp olive oil",
    ],
    pantryIngredients: ["Salt", "Tomato", "Green onions", "Poblano peppers"],
    instructions: [
      "Preheat the oven to 350°F or use a broiler.",
      "Fully cook ground turkey until no longer pink. Add chili and a pinch of salt. Add cheese, tomatoes, and green onions.",
      "Cut the top part of your pepper to remove the stem. Remove the seeds and the insides.",
      "Cut the pepper in half and coat every side with oil.",
      "Line a tray with aluminum foil and place the peppers (with the opening down) on the foil. Place in the oven for about 5 minutes, or until the skin begins to blister.",
      "Carefully remove the peppers from the oven. Remove the foil and flip them back over on the tray or dish. Add your chili filling into the open side.",
    ],
    substitutions: [
      "Use canned beans instead of ground turkey for a vegetarian filling.",
      "Swap poblano peppers for regular bell peppers.",
    ],
  },
  {
    id: "leek-turnip-rice-soup",
    title: "Leek, Turnip, and Rice Soup",
    image: "",
    cookTime: "45 min",
    difficulty: "Easy",
    ingredients: [
      "2 tbsp extra virgin olive oil",
      "4 large leeks, white and light green parts, cleaned and sliced",
      "1 lb turnips, cut in ½ inch dice",
      "2 garlic cloves, minced",
      "2 quarts vegetable stock or water",
      "½ cup rice",
      "2 tbsp chopped fresh parsley",
      "Salt and pepper to taste",
      "1 bay leaf",
    ],
    pantryIngredients: [
      "Leeks",
      "Turnips",
      "Garlic cloves",
      "Vegetable stock",
      "Rice",
      "Fresh parsley",
      "Salt and pepper",
    ],
    instructions: [
      "Heat oil on medium heat in a soup pot and add leeks.",
      "Cook, stirring often, until leeks start to soften, then add turnips. Continue to cook until turnips are translucent and leeks are thoroughly tender.",
      "Stir in the garlic and cook until fragrant.",
      "Add stock or water, salt, bay leaf, and rice.",
      "Bring to a boil, reduce heat to low.",
      "Cover and simmer for 30 minutes, tasting and adjusting for seasonings.",
    ],
    substitutions: [
      "Use any root vegetable (carrots, potatoes) instead of turnips.",
      "Substitute rice with any small pasta or lentils.",
    ],
  },
  {
    id: "vegetable-hand-rolls",
    title: "Vegetable Hand Rolls (Temaki)",
    image: "",
    cookTime: "35 min",
    difficulty: "Medium",
    ingredients: [
      "1 cup (180g) uncooked sushi rice or long grain rice",
      "3 tbsp sushi seasoning",
      "10 sheets toasted sushi nori",
      "½ English cucumber",
      "1 medium red bell pepper",
      "6 oz preserved daikon",
      "2 medium persimmons",
      "2 small avocados, pitted and sliced",
      "Furikake for topping (optional)",
    ],
    pantryIngredients: [
      "Sushi rice",
      "Cucumber",
      "Red bell pepper",
      "Preserved daikon",
      "Persimmons",
      "Avocados",
    ],
    instructions: [
      "Cook the sushi rice. Mix in the sushi seasoning.",
      "While the rice is cooking, prepare the vegetables by cutting them into matchstick-size pieces.",
      "If you want to add persimmons in the hand rolls, peel the persimmons and cut into matchstick-size pieces.",
      "Cut the nori sheets in half. Spoon some rice onto the nori (about 2 to 3 tablespoons). Spread the rice so that you fill one half of the nori.",
      "Top the nori with the sliced vegetables. Roll the nori.",
    ],
    substitutions: [
      "Use regular long-grain rice instead of sushi rice.",
      "Fill with any available crunchy vegetables.",
    ],
  },
  {
    id: "eggplant-curry",
    title: "Eggplant Curry",
    image: "",
    cookTime: "50 min",
    difficulty: "Medium",
    ingredients: [
      "2 large eggplants",
      "3 tbsp oil",
      "1 bunch scallions, finely chopped",
      "1 cup mushrooms, halved",
      "3 garlic cloves, crushed",
      "1 fresh red chili, finely chopped",
      "1 tsp chili powder",
      "1 tbsp curry powder (cumin, coriander, turmeric)",
      "1 tsp salt",
      "14 oz chopped tomatoes",
      "1 tbsp cilantro, chopped (plus extra for garnish)",
    ],
    pantryIngredients: [
      "Eggplants",
      "Scallions",
      "Mushrooms",
      "Garlic",
      "Salt",
      "Chopped tomatoes",
      "Cilantro",
    ],
    instructions: [
      "Preheat the oven to 400°F. Brush each eggplant with 1 tbsp oil and prick with a fork. Bake for 30–35 minutes until soft.",
      "Meanwhile, heat the remaining oil in a saucepan and add scallions, mushrooms, garlic, and chile (optional). Cook for 5 minutes.",
      "Stir in chili powder, curry powder, and salt. Cook 3–4 minutes. Add tomatoes and simmer for 5 minutes.",
      "Once the eggplant is cool enough to touch, cut in half lengthwise and scoop soft flesh into a bowl and mash briefly.",
      "Add the mashed eggplant and chopped cilantro to the pan.",
      "Bring to a boil and simmer for 5 minutes, or until the sauce thickens. Serve garnished with cilantro!",
    ],
    substitutions: [
      "Use zucchini or butternut squash instead of eggplant.",
      "Substitute cilantro with parsley.",
    ],
  },
  {
    id: "pear-pomegranate-salad",
    title: "Pear and Pomegranate Salad",
    image: "",
    cookTime: "10 min",
    difficulty: "Easy",
    ingredients: [
      "¼ cup pomegranate seeds",
      "1 pear, sliced or chopped",
      "3 cups packed baby spinach",
      "¼ cup crumbled feta cheese",
      "¼ cup pecan halves",
      "Optional: orange poppyseed vinaigrette",
      "Vinaigrette: ⅓ cup fresh orange juice, ¼ cup extra virgin olive oil, 1 tbsp dijon mustard, 1 tbsp apple cider vinegar, 1 tbsp poppyseeds, 1 tbsp honey",
    ],
    pantryIngredients: ["Pomegranate seeds", "Pear", "Baby spinach"],
    instructions: [
      "Add the spinach to a large bowl and layer the remaining ingredients on top.",
      "Top with desired dressing or use orange poppyseed vinaigrette.",
      "For the vinaigrette: add all ingredients to a medium jar, tighten the lid, and shake until thoroughly mixed.",
      "Drizzle over salad. Toss to combine. Serve immediately and enjoy!",
    ],
    substitutions: [
      "Swap feta for any crumbled cheese or nutritional yeast.",
      "Use any fresh fruit from the Pantry instead of pear.",
    ],
  },
  {
    id: "garlic-clove-spaghetti",
    title: "Garlic Clove Spaghetti",
    image: "",
    cookTime: "70 min",
    difficulty: "Hard",
    ingredients: [
      "1 lb whole-wheat spaghetti",
      "2 pork loin blade chops",
      "40 cloves fresh garlic, peeled",
      "¼ cup half and half milk",
      "4 tbsp oil",
      "2 tbsp butter",
      "½ tsp crushed red pepper",
      "2 green onions, chopped",
      "Salt and ground pepper to taste",
    ],
    pantryIngredients: [
      "Whole-wheat spaghetti",
      "Garlic cloves",
      "Green onions",
      "Salt and pepper",
    ],
    instructions: [
      "Sauté garlic cloves in oil on low for 40 minutes. Stir often so they roast evenly without burning. Cook until tender and lightly caramelized. Remove garlic and set aside.",
      "In the same pan, add oil and turn heat to medium-high. When oil begins to shimmer, add the pork chops, salt, and pepper. Brown on both sides. Cook on low until cooked through. Remove and set aside.",
      "Cook spaghetti and reserve 1 cup of the pasta water. Set aside. Add 1 tablespoon of butter to the strained spaghetti to prevent sticking.",
      "In a blender, combine garlic and half and half and blend briefly until it has the consistency of hummus.",
      "In a small pan on medium heat, add butter, the garlic mixture, and ¾ cup of the pasta water. Heat and stir until emulsified.",
      "Reheat the pan used for chops on medium-high. Toss in crushed red peppers for 10 seconds, then toss the pasta. Briskly toss to coat pasta with flavors from pork and garlic. Add remaining pasta water and the garlic mixture. Continue to toss until evenly coated.",
    ],
    substitutions: [
      "Use any pasta shape available at the Pantry.",
      "Omit pork for a vegetarian garlic pasta.",
    ],
  },
  {
    id: "orzo-garlicky-spinach",
    title: "Orzo with Garlicky Spinach",
    image: "",
    cookTime: "20 min",
    difficulty: "Easy",
    ingredients: [
      "¾ cup uncooked orzo",
      "1 tbsp butter",
      "4 cups spinach",
      "2 tsp minced garlic",
      "1 oz Parmesan cheese",
      "¼ cup chicken broth",
      "1 tbsp white balsamic vinegar",
      "⅜ tsp salt",
      "¼ tsp crushed red pepper",
    ],
    pantryIngredients: [
      "Orzo",
      "Spinach",
      "Minced garlic",
      "Chicken broth",
      "Salt",
      "Crushed red pepper",
    ],
    instructions: [
      "Cook pasta according to package directions, omitting salt and fat.",
      "Melt butter over medium heat. Cook for 1 minute or until browned.",
      "Add spinach and minced garlic. Cook for 1 minute.",
      "Stir in orzo, Parmesan cheese, chicken broth, vinegar, salt, and crushed red pepper.",
    ],
    substitutions: [
      "Use any small pasta shape instead of orzo.",
      "Use vegetable broth for a vegetarian version.",
    ],
  },
  {
    id: "udon-chicken-peanut-dressing",
    title: "Udon with Chicken and Garlicky Peanut Dressing",
    image: "",
    cookTime: "25 min",
    difficulty: "Medium",
    ingredients: [
      "¼ cup natural creamy peanut butter",
      "¼ cup soy sauce",
      "¼ cup unseasoned rice vinegar",
      "1 tbsp honey",
      "1 garlic clove, finely grated",
      "¼ cup vegetable oil",
      "8 oz dried udon noodles",
      "Kosher salt",
      "8 oz shredded rotisserie chicken (about 2 cups)",
      "1½ cups thinly sliced celery hearts and leaves",
      "1½ cups mung bean sprouts",
      "1 small daikon, peeled, cut into matchsticks",
      "2 tsp black and/or white sesame seeds",
      "Chili oil (for serving)",
    ],
    pantryIngredients: [
      "Natural creamy peanut butter",
      "Garlic",
      "Celery hearts",
      "Mung bean sprouts",
      "Daikon",
    ],
    instructions: [
      "Whisk peanut butter, soy sauce, vinegar, honey, and garlic in a small bowl until smooth. Gradually add vegetable oil, whisking constantly until emulsified. Set aside.",
      "Cook noodles in a large saucepan of boiling salted water according to package instructions until al dente. Drain; rinse under cold water, then drain again.",
      "Toss noodles, chicken, celery, bean sprouts, and daikon in a large bowl with three-quarters of the reserved dressing to combine and evenly coat. Season with salt.",
      "Top with sesame seeds and drizzle remaining dressing and chili oil over.",
    ],
    substitutions: [
      "Use any noodle available at the Pantry.",
      "Substitute chicken with canned tuna or chickpeas.",
    ],
  },
  {
    id: "roasted-tomato-avocado-toast",
    title: "Roasted Tomato Avocado Toast",
    image: "",
    cookTime: "30 min",
    difficulty: "Easy",
    ingredients: [
      "3 tomatoes",
      "4 slices bread of your choice",
      "2 ripe avocados",
      "Juice from 1 lime",
      "Flat leaf parsley for garnish",
      "Italian seasoning",
      "Olive oil",
      "Red pepper flakes (optional)",
      "Balsamic vinegar",
      "Sea salt",
    ],
    pantryIngredients: [
      "Tomatoes",
      "Bread",
      "Avocados",
      "Flat leaf parsley",
      "Sea salt",
    ],
    instructions: [
      "Preheat the oven to 375°F. Slice tomatoes and place on a baking pan. Sprinkle with Italian seasoning and sea salt, then drizzle with olive oil. Roast for 15–20 minutes.",
      "While the tomatoes are roasting, cut the avocados in half, remove the pit, and scoop the flesh into a medium bowl. Add the lime juice and mash the avocados to desired texture.",
      "Toast the bread in a toaster or in the oven.",
      "Spread the avocado mash over the toast, place slices of tomato over the avocado, drizzle with balsamic glaze, and garnish with flat leaf parsley and red pepper flakes.",
      "Serve immediately and enjoy!",
    ],
    substitutions: [
      "Use any available bread type.",
      "Top with a fried or poached egg for extra protein.",
    ],
  },
  {
    id: "corn-salad-radish-jalapeno",
    title: "Corn Salad with Radishes, Jalapeño, and Lime",
    image: "",
    cookTime: "10 min",
    difficulty: "Easy",
    ingredients: [
      "1½ cans of corn",
      "6 radishes",
      "½ jalapeño (or whole)",
      "3 tbsp lime juice",
      "2 tbsp cilantro leaves",
      "1½ tbsp olive oil",
      "Salt to taste",
    ],
    pantryIngredients: [
      "Corn (canned)",
      "Radishes",
      "Jalapeño",
      "Cilantro",
    ],
    instructions: [
      "Chop radishes, jalapeño, and cilantro leaves to your preference.",
      "Combine all ingredients in a bowl. Season with salt to taste.",
      "Salad can be stored in the fridge for 1 day.",
    ],
    substitutions: [
      "Use frozen corn instead of canned.",
      "Omit jalapeño for a milder version.",
    ],
  },
  {
    id: "butternut-squash-soup",
    title: "Butternut Squash Soup",
    image: "",
    cookTime: "50 min",
    difficulty: "Easy",
    ingredients: [
      "2 tbsp butter",
      "1 medium white or yellow onion, peeled and diced",
      "1 medium butternut squash, peeled, seeded, and cubed",
      "1 medium carrot, peeled and chopped",
      "1 stalk celery, chopped",
      "2 medium potatoes, cubed",
      "23 oz vegetable broth or chicken stock",
      "Salt and pepper to taste",
    ],
    pantryIngredients: [
      "White or yellow onion",
      "Butternut squash",
      "Carrot",
      "Celery",
      "Potatoes",
      "Vegetable broth or chicken stock",
      "Salt and pepper",
    ],
    instructions: [
      "Melt the butter in a large pot over medium-high heat. Sauté chopped onions until lightly browned.",
      "Season with salt and pepper. Add in all the chopped vegetables.",
      "Pour enough vegetable broth or chicken stock to cover vegetables and bring to a boil.",
      "Reduce heat to low, cover pot, and simmer for 40 minutes.",
      "Purée using an immersion blender, or transfer in batches to a food processor or blender. Blend until smooth.",
      "Return to pot and mix in any remaining stock to attain desired consistency.",
    ],
    substitutions: [
      "Swap butternut squash for pumpkin or sweet potato.",
      "Use olive oil instead of butter.",
    ],
  },
  {
    id: "butternut-squash-basmati-rice",
    title: "Butternut Squash Basmati Rice",
    image: "",
    cookTime: "25 min",
    difficulty: "Easy",
    ingredients: [
      "1 tbsp unsalted butter",
      "1 tsp whole cumin seeds (or cumin powder)",
      "1 tsp mustard seeds (or wasabi or mustard powder)",
      "1 cup basmati rice",
      "2 cups water",
      "¾ lb butternut squash, peeled and cut into ¼ inch cubes",
      "2 tsp salt",
    ],
    pantryIngredients: ["Basmati rice", "Butternut squash", "Salt"],
    instructions: [
      "In a medium saucepan, melt butter. Add cumin and mustard seeds and cook over high heat until mustard seeds begin to pop (about 30 seconds).",
      "Add rice and diced squash. Stir to coat with butter. Add water and salt. Bring to a boil.",
      "Cover and cook over very low heat until squash is tender and water is absorbed (about 15 minutes).",
      "Remove from heat and let the rice stand, covered, for 5 minutes.",
      "Fluff the rice with a fork and serve.",
    ],
    substitutions: [
      "Use any rice variety available at the Pantry.",
      "Substitute butternut squash with sweet potato.",
    ],
  },
  {
    id: "chicken-sweet-potato-black-bean-skillet",
    title: "Chicken, Sweet Potato, and Black Bean Skillet",
    image: "",
    cookTime: "30 min",
    difficulty: "Medium",
    ingredients: [
      "1 sweet potato, peeled and diced",
      "1 cup cherry tomatoes, halved",
      "½ cup diced onion",
      "½ cup diced green chilis",
      "1 lb boneless skinless chicken breasts, cut into bite-sized pieces",
      "1 can black beans, rinsed and drained",
      "⅓ cup salsa or red enchilada sauce",
      "½ cup shredded cheddar/jack cheese",
      "2 tsp olive oil",
      "½ lime, juiced",
      "1 tbsp cilantro (optional)",
      "1 tsp each: ground cumin, chili powder, oregano",
      "¼ tsp each: granulated garlic, pepper",
    ],
    pantryIngredients: [
      "Sweet potato",
      "Diced onion",
      "Diced green chilis",
      "Black beans (canned)",
      "Ground cumin",
      "Granulated garlic",
      "Pepper",
    ],
    instructions: [
      "Heat oil in a large cast iron or non-stick skillet over medium-high heat. Combine all spices in a small bowl.",
      "When the skillet is hot, add in the chicken and spread into an even layer, then sprinkle with half of the spice blend.",
      "Sauté the chicken for approximately 3 minutes, then add in the onion.",
      "Continue to cook for several more minutes until the onion has softened and the chicken is cooked through.",
      "Lower the heat to medium and add the remaining spice blend, sweet potato, cherry tomatoes, black beans, green chilis, and salsa. Stir mixture and cook until heated through, about 2–3 minutes.",
      "Squeeze lime juice over everything, then top with shredded cheese.",
      "Cover with a lid or foil until the cheese has melted. Garnish with cilantro and serve.",
    ],
    substitutions: [
      "Use canned chickpeas instead of chicken for a vegetarian version.",
      "Swap black beans for any canned beans from the Pantry.",
    ],
  },
  {
    id: "lima-bean-soup",
    title: "Lima Bean Soup",
    image: "",
    cookTime: "35 min",
    difficulty: "Easy",
    ingredients: [
      "3 cans chicken broth",
      "2 cans lima beans, rinsed and drained",
      "3 medium carrots",
      "2 medium potatoes",
      "2 small onions",
      "2 small sweet red peppers",
      "¼ cup butter",
      "Salt, pepper, oregano",
      "1 cup half and half cream",
    ],
    pantryIngredients: [
      "Chicken broth",
      "Lima beans (canned)",
      "Carrots",
      "Potatoes",
      "Onions",
      "Sweet red peppers",
      "Salt, pepper, oregano",
    ],
    instructions: [
      "In a large pot, combine all ingredients. Bring to a boil over medium heat.",
      "Reduce heat, cover, and simmer for 25–35 minutes.",
      "Add cream and heat through but do not boil.",
    ],
    substitutions: [
      "Use vegetable broth for a vegetarian version.",
      "Substitute lima beans with any canned white beans.",
    ],
  },
  {
    id: "okra-chickpeas-tomato-sauce",
    title: "Okra and Chickpeas in Fresh Tomato Sauce",
    image: "",
    cookTime: "30 min",
    difficulty: "Easy",
    ingredients: [
      "2 tbsp extra-virgin olive oil",
      "1 medium yellow onion, chopped",
      "2 garlic cloves, very finely chopped",
      "5 ripe tomatoes, cored and chopped",
      "1 tbsp ground cumin",
      "1 tbsp harissa (or Sriracha)",
      "1 tsp lemon zest, plus 1 tbsp fresh lemon juice",
      "1 lb fresh okra, stems trimmed, cut into ½-inch slices",
      "1½ tsp kosher salt, divided",
      "¾ tsp black pepper, divided",
      "1 (15.5 oz) can chickpeas, drained and rinsed",
      "¼ cup chopped fresh flat-leaf parsley",
    ],
    pantryIngredients: [
      "Yellow onion",
      "Garlic",
      "Tomatoes",
      "Ground cumin",
      "Fresh okra",
      "Salt",
      "Black pepper",
      "Chickpeas (canned)",
      "Fresh parsley",
    ],
    instructions: [
      "Heat oil in a large skillet over medium-low. Add yellow onion and cook, stirring often, until soft and translucent, about 6 minutes.",
      "Add garlic and cook, stirring often, until fragrant, 45–60 seconds.",
      "Add tomatoes, cumin, harissa, lemon zest, and lemon juice. Cook, stirring once or twice, until tomatoes start to break down, about 5 minutes.",
      "Add okra, 1 tsp of the salt, and ½ tsp of the pepper. Reduce heat to low and cover. Cook, stirring occasionally, until okra is just tender, about 10 minutes.",
      "Add chickpeas and stir to combine. Cover and cook just until chickpeas are heated through, about 3 minutes.",
      "Stir in chopped parsley and remaining salt and pepper. Serve immediately.",
    ],
    substitutions: [
      "Use frozen okra if fresh is unavailable.",
      "Add spinach or kale for extra greens.",
    ],
  },
  {
    id: "creamy-tomato-basil-soup",
    title: "Creamy Tomato Basil Soup",
    image: "",
    cookTime: "30 min",
    difficulty: "Easy",
    ingredients: [
      "2 tbsp oil",
      "2 tbsp unsalted butter",
      "1 yellow onion, chopped",
      "2 cloves garlic, minced",
      "1 tsp kosher salt",
      "½ tsp pepper",
      "2 tbsp flour",
      "4 cans vegetable broth",
      "1 can whole peeled tomatoes",
      "3 oz tomato paste",
      "1 tsp sugar",
      "1 cup heavy cream",
      "5 basil leaves, chopped",
    ],
    pantryIngredients: ["Yellow onion", "Garlic", "Salt", "Pepper"],
    instructions: [
      "Add the oil and butter to a pan on medium heat.",
      "Add the onion and garlic and cook for 2–3 minutes or until translucent.",
      "Add salt, pepper, and flour. Whisk well until the flour is cooked for roughly 30 seconds and fully incorporated.",
      "Add in the broth slowly while whisking. Add in the tomatoes, tomato paste, and sugar. Add in chopped basil leaves.",
      "Lower the heat to low and let cook for 20 minutes.",
      "Using a blender, pour soup contents and blend until completely smooth.",
      "Add in the cream and let cook for an additional 5 minutes before serving.",
      "Serve with grilled cheese for a comforting dish!",
    ],
    substitutions: [
      "Use coconut milk instead of heavy cream for a dairy-free version.",
      "Add canned white beans for extra protein.",
    ],
  },
  {
    id: "cilantro-rice",
    title: "Cilantro Rice",
    image: "",
    cookTime: "30 min",
    difficulty: "Easy",
    ingredients: [
      "1 cup rice",
      "2 dried bay leaves (or fresh)",
      "1½ cups water",
      "2 tbsp lime juice",
      "Salt to taste",
      "½ cup chopped fresh cilantro",
      "1 tsp lemon juice (optional)",
    ],
    pantryIngredients: ["Rice", "Water", "Salt", "Fresh cilantro"],
    instructions: [
      "In a saucepan, add rice, bay leaves, and water. Bring to a boil.",
      "Once boiling, reduce the heat, cover, and simmer for 18 minutes.",
      "Remove lid, fluff rice with fork, and cover. Let rest and absorb any steam for 10 minutes.",
      "Remove bay leaves, add lime juice, lemon juice, salt, and cilantro. Stir to combine.",
    ],
    substitutions: [
      "Use any rice variety from the Pantry.",
      "Substitute cilantro with fresh parsley.",
    ],
  },
  {
    id: "moringa-stir-fry",
    title: "Moringa Leaves Stir-Fry (Thoran) with Grated Coconut",
    image: "",
    cookTime: "25 min",
    difficulty: "Easy",
    ingredients: [
      "250 grams moringa (drumstick) leaves",
      "¼ cup grated coconut",
      "Salt to taste",
      "1 tbsp oil",
      "½ tsp mustard seeds",
      "¼ cup shallots",
      "1 tbsp crushed dried chilies",
      "1 sprig curry leaves (optional)",
      "¼ tsp turmeric powder (optional)",
    ],
    pantryIngredients: [],
    instructions: [
      "Wash and drain the moringa leaves. Get rid of all the thick sprigs.",
      "Crush the shallots with the flat surface of your knife. Finely chop shallots.",
      "Take the moringa leaves, grated coconut, turmeric powder, and salt in a mixing bowl. Combine well.",
      "Heat the oil in a pan. Add mustard seeds, then the chopped shallots.",
      "After the shallots are cooked to tender, add crushed chillies and curry leaves (optional). Sauté for a couple of minutes on medium heat.",
      "Add the mixed moringa leaves and combine well.",
      "Cook with the lid closed for 10 minutes. Add salt if required. Stir occasionally.",
      "Open the lid, stir well, and cook for 2 minutes.",
      "Switch off, and serve hot with some rice and curry.",
    ],
    substitutions: [
      "Serve over pantry rice for a complete meal.",
      "Add canned chickpeas for extra protein.",
    ],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return pantryRecipes.find((r) => r.id === id);
}

export function searchRecipes(query: string): Recipe[] {
  const q = query.toLowerCase();
  return pantryRecipes.filter(
    (r) =>
      r.title.toLowerCase().includes(q) ||
      r.pantryIngredients.some((i) => i.toLowerCase().includes(q)) ||
      r.ingredients.some((i) => i.toLowerCase().includes(q))
  );
}

export function scoreRecipe(recipe: Recipe, userIngredients: string[]): number {
  if (userIngredients.length === 0 || recipe.pantryIngredients.length === 0)
    return 0;
  const normalized = userIngredients.map((i) => i.toLowerCase());
  const matches = recipe.pantryIngredients.filter((pi) =>
    normalized.some(
      (ui) =>
        pi.toLowerCase().includes(ui) || ui.includes(pi.toLowerCase())
    )
  );
  return Math.round((matches.length / recipe.pantryIngredients.length) * 100);
}
